[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/keyword"
  to = "/.netlify/functions/keyword"
  status = 200

[[redirects]]
  from = "/api/seo"
  to = "/.netlify/functions/seo"
  status = 200
